apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: musical-service-secret
  namespace: truve-musical-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: truve-secret-store
    kind: ClusterSecretStore
  target:
    name: musical-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/musical-service