# Jaeger All-in-One 설정
allInOne:
  enabled: true
  storage:
    type: memory # allInOne 내부로 이동
  image:
    repository: jaegertracing/all-in-one
    tag: 1.55.0

  # 모니터링 노드 설정
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: workload
      operator: Equal
      value: monitoring
      effect: NoSchedule

  # OTEL Collector로부터 데이터를 받기 위한 포트 설정
  extraPorts:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP

# 서비스 이름 고정
fullnameOverride: jaeger
