storage:
  type: elasticsearch
  elasticsearch:
    host: elasticsearch-master.logging.svc.cluster.local
    port: 9200

allInOne:
  enabled: false

collector:
  enabled: true
  replicaCount: 2
  service:
    otlp:
      grpc: { enabled: true }
      http: { enabled: true }
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: workload
      operator: Exists
      effect: NoSchedule

query:
  enabled: true
  replicaCount: 2
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: workload
      operator: Exists
      effect: NoSchedule
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/group.name: monitoring
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:599476212908:certificate/c777a244-2261-47b1-aea0-0f68c9fb5249
      alb.ingress.kubernetes.io/ssl-redirect: "443"
    hosts:
      - jaeger.truve.site
    paths:
      - /

cassandra: { enabled: false }

fullnameOverride: jaeger
