triggerAuthentication:
  enabled: false # 외부 인증이 필요한 scaler면 true로 바꾸고 사용하면 됨
  name: keda-trigger-auth # TriggerAuthentication 이름

scaledObjects: # 여러 ScaledObject 설정을 한 곳에서 관리하기 위한 구조
  - name: gateway-service-gateway-service
    namespace: truve-gateway-service
    enabled: true # ScaledObject 생성 여부
    scaleTargetRef:
      name: gateway-service-gateway-service
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 30
    cooldownPeriod: 300
    type: prometheus # Prometheus의 HTTP 요청량 기준으로 스케일링
    prometheus:
      serverAddress: http://prometheus-operated.observability.svc.cluster.local:9090 # Prometheus가 클러스터 내에 설치돼 있고, Service 이름이 prometheus-operated인 경우
      metricName: http_requests_per_second # KEDA 내부 메트릭 이름
      query: sum(rate(http_requests_total{app="app-api"}[2m])) # app="app-api" 라벨이 붙은 HTTP 요청 수를 2분간의 평균으로 계산
      threshold: '20' # 이 threshold를 넘으면 scale out

  - name: queue-service-queue-service # Kafka 기반 스케일링 설정
    namespace: truve-queue-service
    enabled: false # kafka consumer/worker용 ScaledObject 생성 여부
    scaleTargetRef:
      name: queue-service-queue-service
    minReplicaCount: 0 # worker는 이벤트 없으면 0까지 줄일 수 있음
    maxReplicaCount: 20
    pollingInterval: 15
    cooldownPeriod: 120
    type: kafka # Kafka의 lag 기준으로 스케일링
    kafka:
      bootstrapServers: kafka-headless.truve-kafka.svc.cluster.local:9092 # Kafka bootstrap 서버 주소
      consumerGroup: worker-group # lag를 볼 consumer group 이름
      topic: worker-topic # 감시할 topic 이름
      lagThreshold: '10' # lag(컨슈머가 아직 읽지 않은 메시지 수)가 이 값 이상이면 scale out
      offsetResetPolicy: latest # offset 초기화 정책

  - name: ticketing-service-ticketing-service
    namespace: truve-ticketing-service
    enabled: false
    scaleTargetRef:
      name: ticketing-service-ticketing-service
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 30
    cooldownPeriod: 300
    type: prometheus
    prometheus:
      serverAddress: http://prometheus-operated.observability.svc.cluster.local:9090
      metricName: http_requests_per_second
      query: sum(rate(http_requests_total{app="ticketing-service"}[2m]))
      threshold: '20'

  - name: auth-service-auth-service
    namespace: truve-auth-service
    enabled: false
    scaleTargetRef:
      name: auth-service-auth-service
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 30
    cooldownPeriod: 300
    type: prometheus
    prometheus:
      serverAddress: http://prometheus-operated.observability.svc.cluster.local:9090
      metricName: http_requests_per_second
      query: sum(rate(http_requests_total{app="auth-service"}[2m]))
      threshold: '20'
