replicaCount: 3

image:
  repository: kye8780/api-gateway
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:599476212908:certificate/c777a244-2261-47b1-aea0-0f68c9fb5249
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: "8080"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
  hosts:
    - host: gateway.truve.site
      paths:
        - path: /
          pathType: Prefix

config:
  auth_server_uri: "http://auth-service.truve-auth-service.svc.cluster.local:8081"
  payment_server_uri: "http://payment-service.truve-payment-service.svc.cluster.local:8082"
  queue_server_uri: "http://queue-service.truve-queue-service.svc.cluster.local:8083"
  ticketing_server_uri: "http://ticketing-service.truve-ticketing-service.svc.cluster.local:8084"
  musical_server_uri: "http://musical-service.truve-musical-service.svc.cluster.local:8085"
  user_redis_host: "redis-headless.truve-redis.svc.cluster.local"
  user_redis_port: "6379"
  spring_data_redis_cluster_nodes: "redis-headless.truve-redis.svc.cluster.local:6379"
  spring_data_redis_cluster_max_redirects: "10"
  spring_data_redis_cluster_refresh_adaptive: "true"
  spring_data_redis_cluster_refresh_period: "30s"