apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      nodeSelector:
        workload: app

      initContainers:
        - name: copy-otel-agent
          image: busybox:1.36
          command: ["sh", "-c", "wget https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar -O /otel/opentelemetry-javaagent.jar"]
          volumeMounts:
            - name: otel-agent
              mountPath: /otel
      containers:
        - name: gateway-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: AUTH_SERVER_URI
              value: {{ .Values.config.auth_server_uri | quote }}
            - name: PAYMENT_SERVER_URI
              value: {{ .Values.config.payment_server_uri | quote }}
            - name: QUEUE_SERVER_URI
              value: {{ .Values.config.queue_server_uri | quote }}
            - name: TICKETING_SERVER_URI
              value: {{ .Values.config.ticketing_server_uri | quote }}
            - name: MUSICAL_SERVER_URI
              value: {{ .Values.config.musical_server_uri | quote }}
            - name: USER_REDIS_HOST
              value: {{ .Values.config.user_redis_host | quote }}
            - name: USER_REDIS_PORT
              value: {{ .Values.config.user_redis_port | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gateway-service-secret
                  key: JWT_SECRET

            - name: SPRINGDOC_SWAGGER_UI_URLS_0_NAME
              value: "01-Auth Service"
            - name: SPRINGDOC_SWAGGER_UI_URLS_0_URL
              value: "/api/auth/v3/api-docs"

            - name: SPRINGDOC_SWAGGER_UI_URLS_1_NAME
              value: "02-Payment Service"
            - name: SPRINGDOC_SWAGGER_UI_URLS_1_URL
              value: "/api/payments/v3/api-docs"

            - name: SPRINGDOC_SWAGGER_UI_URLS_2_NAME
              value: "03-Queue Service"
            - name: SPRINGDOC_SWAGGER_UI_URLS_2_URL
              value: "/api/queue/v3/api-docs"

            - name: SPRINGDOC_SWAGGER_UI_URLS_3_NAME
              value: "04-Ticketing Service"
            - name: SPRINGDOC_SWAGGER_UI_URLS_3_URL
              value: "/api/ticketing/v3/api-docs/ticketing"

            - name: SPRINGDOC_SWAGGER_UI_URLS_4_NAME
              value: "05-Booking Service"
            - name: SPRINGDOC_SWAGGER_UI_URLS_4_URL
              value: "/api/ticketing/v3/api-docs/booking"

            - name: SPRINGDOC_SWAGGER_UI_URLS_5_NAME
              value: "06-Musical Service"
            - name: SPRINGDOC_SWAGGER_UI_URLS_5_URL
              value: "/api/shows/v3/api-docs"
            - name: OTEL_SERVICE_NAME
              value: "gateway-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-opentelemetry-collector.observability:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel/opentelemetry-javaagent.jar"

          volumeMounts:
            - name: otel-agent
              mountPath: /otel
      volumes:
        - name: otel-agent
          emptyDir: {}