apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-service-secret
  namespace: truve-gateway-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: truve-secret-store
    kind: ClusterSecretStore
  target:
    name: gateway-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/gateway-service