apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd-vs
  namespace: argocd
spec:
  hosts:
    - "argocd.truve.site"
  gateways:
    - istio-system/truve-gateway
  http:
    - route:
        - destination:
            host: argocd-server
            port:
              number: 80
