kube-prometheus-stack:
  prometheusOperator:
    nodeSelector:
      eks.amazonaws.com/nodegroup: truve-monitor-prod-ng

  grafana:
    nodeSelector:
      eks.amazonaws.com/nodegroup: truve-monitor-prod-ng
    persistence:
      enabled: true
      storageClassName: gp3
      size: 10Gi
    ingress:
      enabled: true
      ingressClassName: alb
      annotations:
        alb.ingress.kubernetes.io/group.name: monitoring
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:599476212908:certificate/c777a244-2261-47b1-aea0-0f68c9fb5249
        alb.ingress.kubernetes.io/ssl-redirect: "443"
        alb.ingress.kubernetes.io/success-codes: 200,302
      hosts:
        - grafana.truve.site
      paths:
        - /
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        searchNamespace: ALL

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
    ingress:
      enabled: true
      ingressClassName: alb
      annotations:
        alb.ingress.kubernetes.io/group.name: monitoring
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:599476212908:certificate/c777a244-2261-47b1-aea0-0f68c9fb5249
        alb.ingress.kubernetes.io/ssl-redirect: "443"
      hosts:
        - prometheus.truve.site
      paths:
        - /
      pathType: Prefix
  
  alertmanager:
    alertmanagerSpec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: truve-monitor-prod-ng

  kube-state-metrics:
    nodeSelector:
      eks.amazonaws.com/nodegroup: truve-monitor-prod-ng

  prometheus-node-exporter: {}