grafana:
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: workload
      operator: Exists
      effect: NoSchedule
  persistence:
    enabled: true
    storageClassName: gp3
    accessModes: ['ReadWriteOnce']
    size: 10Gi
  adminUser: admin
  adminPassword: truve#12

  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.observability.svc.cluster.local:3100
      jsonData:
        maxLines: 1000
    - name: Jaeger
      type: jaeger
      access: proxy
      url: http://jaeger-query.observability.svc.cluster.local:80
      jsonData:
        nodeGraph:
          enabled: true

prometheus:
  prometheusSpec:
    nodeSelector:
      workload: monitoring
    tolerations:
      - key: workload
        operator: Exists
        effect: NoSchedule
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ['ReadWriteOnce']
          resources:
            requests:
              storage: 50Gi

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      workload: monitoring
    tolerations:
      - key: workload
        operator: Exists
        effect: NoSchedule
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ['ReadWriteOnce']
          resources:
            requests:
              storage: 10Gi

kubeStateMetrics:
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: workload
      operator: Exists
      effect: NoSchedule

prometheusOperator:
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: workload
      operator: Exists
      effect: NoSchedule

nodeExporter:
  tolerations:
    - operator: Exists
