{{- if .Values.triggerAuthentication.enabled }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Values.triggerAuthentication.name | quote }} # KEDA Scaler가 외부 비밀/인증 정보를 참조할 때 사용하는 리소스
  namespace: {{ .Release.Namespace | quote }} # 별도 values 없이 현재 Helm 릴리스 namespace에 생성

spec: {} # 지금은 비워두고, 필요 시 secretTargetRef / podIdentity / env 등으로 확장
{{- end }}
