{{- if .Values.triggerAuthentication.enabled }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Values.triggerAuthentication.name }}
  namespace: {{ .Values.namespace }}
spec: {}
{{- end }}