apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: tempo
      targetRevision: 1.26.1
      helm:
        valueFiles:
          - $values/chart/observability/tempo/values.yaml
    - repoURL: https://github.com/pain22value/truve-k8s-resources.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  ignoreDifferences: # PVC의 생성 시점에 따라 생성 Timestamp가 달라져서 ArgoCD가 null 같은 필드 차이를 OutOfSync로 인식하는 문제 해결
    - group: apps
      kind: StatefulSet
      name: tempo
      namespace: observability
      jsonPointers:
        - /spec/volumeClaimTemplates/0/metadata/creationTimestamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
