# Kafka가 의존하는 메타데이터 관리
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
spec:
  clusterIP: None
  selector:
    app: zookeeper
  ports:
    - name: client
      port: {{ .Values.zookeeper.port }}
      targetPort: {{ .Values.zookeeper.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  ports:
    - name: client
      port: {{ .Values.zookeeper.port }}
      targetPort: {{ .Values.zookeeper.port }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper-headless
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image | quote }}
          imagePullPolicy: IfNotPresent

          ports:
            - name: client
              containerPort: {{ .Values.zookeeper.port }}

          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: {{ .Values.zookeeper.port | quote }}
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
