# Kafka가 의존하는 메타데이터 관리
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
spec:
  clusterIP: None
  ports:
    - name: client
      port: { { .Values.zookeeper.port } }
      targetPort: { { .Values.zookeeper.port } }
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  ports:
    - name: client
      port: { { .Values.zookeeper.port } }
      targetPort: { { .Values.zookeeper.port } }
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper-headless
  replicas: { { .Values.zookeeper.replicaCount } }
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      nodeSelector: { { - toYaml .Values.nodeSelector | nindent 8 } }

      tolerations: { { - toYaml .Values.tolerations | nindent 8 } }

      affinity: { { - toYaml .Values.affinity | nindent 8 } }

      containers:
        - name: zookeeper
          image: { { .Values.zookeeper.image } }
          imagePullPolicy: IfNotPresent

          ports:
            - name: client
              containerPort: { { .Values.zookeeper.port } }

          resources: { { - toYaml .Values.zookeeper.resources | nindent 12 } }

          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: '{{ .Values.zookeeper.port }}'
            - name: ZOOKEEPER_TICK_TIME
              value: '{{ .Values.zookeeper.tickTime | default 2000 | quote }}'

          volumeMounts:
            - name: zookeeper-data
              mountPath: /var/lib/zookeeper/data

  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: { { .Values.zookeeper.persistence.storageClass } }
        resources:
          requests:
            storage: { { .Values.zookeeper.persistence.size } }
