apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/pain22value/truve-k8s-resources.git
    targetRevision: HEAD
    path: chart/karpenter
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter

  syncPolicy:
    automated:
      prune: true # Git에서 삭제되면 클러스터에서도 삭제
      selfHeal: true # 클러스터에서 수동 변경돼도 Git 상태로 복원

