apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: 2.19.0
    helm:
      releaseName: keda

  destination:
    server: https://kubernetes.default.svc
    namespace: keda

  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - CreateNamespace=true # namespace가 없으면 자동으로 생성하도록 하는 옵션
  #     - ServerSideApply=true # KEDA Helm 차트는 Server-Side Apply를 활용하여 리소스를 관리하므로 이 옵션을 활성화해야 함
