apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-running.slack: C0AKYEYK86Q
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: C0AKYEYK86Q
    notifications.argoproj.io/subscribe.on-sync-failed.slack: C0AKYEYK86Q
    notifications.argoproj.io/subscribe.on-health-degraded.slack: C0AKYEYK86Q
spec:
  project: default
  source:
    repoURL: https://github.com/pain22value/truve-k8s-resources
    targetRevision: HEAD
    path: chart/payment-service
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: truve-payment-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
