apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticketing-service
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-running.slack: C0AKYEYK86Q
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: C0AKYEYK86Q
    notifications.argoproj.io/subscribe.on-sync-failed.slack: C0AKYEYK86Q
    notifications.argoproj.io/subscribe.on-health-degraded.slack: C0AKYEYK86Q
    argocd-image-updater.argoproj.io/image-list: truve-ticketing=599476212908.dkr.ecr.ap-northeast-2.amazonaws.com/truve/ticketing
    argocd-image-updater.argoproj.io/truve-ticketing.update-strategy: latest
    argocd-image-updater.argoproj.io/truve-ticketing.allow-tags: |
      regexp:^[0-9a-f]{40}$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:chart/ticketing-service/values.yaml
spec:
  project: default
  source:
    repoURL: https://github.com/pain22value/truve-k8s-resources
    targetRevision: HEAD
    path: chart/ticketing-service
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: truve-ticketing-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
