apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-auth-config
data:
  application-prod.yaml: |-
    spring:
      datasource:
        url: {{ .Values.config.SPRING_DATASOURCE_URL | quote }}