apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-secret
  namespace: truve-auth-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: truve-secret-store
    kind: ClusterSecretStore
  target:
    name: auth-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/auth-service