replicaCount: 3

image:
  repository: kye8780/queue
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

service:
  type: ClusterIP
  port: 8083

ingress:
  enabled: false

config:
  logging.level.org.springframework.data.redis: "TRACE"
  logging.level.io.lettuce.core: "DEBUG"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATA_REDIS_CLUSTER_NODES: "redis-headless.truve-redis.svc.cluster.local:6379"
  SPRING_DATA_REDIS_CLUSTER_MAX_REDIRECTS: "10"
  SPRING_DATA_REDIS_CLUSTER_REFRESH_ADAPTIVE: "true"
  SPRING_DATA_REDIS_CLUSTER_REFRESH_PERIOD: "30s"