replicaCount: 1

image:
  repository: 599476212908.dkr.ecr.ap-northeast-2.amazonaws.com/truve/queue
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

service:
  type: ClusterIP
  port: 8083

ingress:
  enabled: false

config:
  logging.level.org.springframework.data.redis: "WARN"
  logging.level.io.lettuce.core: "WARN"
  logging.level.org.springframework.data.redis.connection: "WARN"
  logging.level.org.springframework.data.redis.core: "WARN"
  logging.level.io.lettuce.core.protocol: "WARN"
  logging.level.io.lettuce.core.cluster: "WARN"
  logging.level.io.netty: "WARN"
  logging.level.com.truve: "INFO"
  logging.level.root: "INFO"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATA_REDIS_HOST: "redis.truve-redis.svc.cluster.local"
  SPRING_DATA_REDIS_PORT: "6379"