apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-queue-config
data:
  application-prod.yaml: |-
    spring:
      data:
        redis:
          host: {{ .Values.config.SPRING_DATA_REDIS_HOST | quote }}
          port: {{ .Values.config.SPRING_DATA_REDIS_PORT }}
          cluster:
            enabled: false