replicaCount: 1

image:
  repository: kye8780/payment
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

ingress:
  enabled: false

config:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:mysql://truve-mysql-test.c14q2m426g1v.ap-northeast-2.rds.amazonaws.com:3306/payment_db"