mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.96.0

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    memory_limiter:
      check_interval: 1s
      limit_mib: 850 # 리소스 제한의 약 85%
      spike_limit_mib: 100
    batch:
      send_batch_size: 1000
      timeout: 10s

  exporters:
    # Jaeger로 Traces 데이터 전송
    otlp/jaeger:
      endpoint: jaeger.observability.svc.cluster.local:4317
      tls:
        insecure: true
    # Prometheus가 긁어갈 수 있도록 메트릭 노출
    prometheus:
      endpoint: '0.0.0.0:8890'
    # 디버깅용 (로그로 데이터 확인 가능)
    debug: {}

  extensions:
    health_check:
      endpoint: 0.0.0.0:13133

  service:
    extensions: [health_check]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [otlp/jaeger, debug]
      metrics:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [prometheus]

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi

nodeSelector:
  workload: monitoring

tolerations:
  - key: 'workload'
    operator: 'Exists'
    effect: 'NoSchedule'

##############################################
# opentelemetry-collector Helm chart는 config 안의 기본 receiver/exporter를 보고 필요한 포트를 자동으로 활성화한다. 공식 문서에도 기본 설정에 따라 포트가 자동으로 켜지고, 필요하면 ports에서 비활성화할 수 있다고 되어 있다. 따라서 ports 설정은 생략하여 기본 포트가 활성화되도록 한다.
##############################################
# ports:
#   otlp-grpc:
#     enabled: true
#     containerPort: 4317
#     servicePort: 4317
#     protocol: TCP
#   otlp-http:
#     enabled: true
#     containerPort: 4318
#     servicePort: 4318
#     protocol: TCP
#   prometheus:
#     enabled: true
#     containerPort: 8889
#     servicePort: 8889
#     protocol: TCP
