replicaCount: 3

image:
  repository: kye8780/auth-server
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: false

config:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:mysql://dev-mysql.c14q2m426g1v.ap-northeast-2.rds.amazonaws.com:3306/user_db"
  SPRING_DATA_REDIS_CLUSTER_NODES: "redis-headless.truve-redis.svc.cluster.local:6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service.truve-kafka.svc.cluster.local:9092"
  SPRING_DATA_REDIS_CLUSTER_MAX_REDIRECTS: "10"
  SPRING_DATA_REDIS_CLUSTER_REFRESH_ADAPTIVE: "true"
  SPRING_DATA_REDIS_CLUSTER_REFRESH_PERIOD: "30s"

  logging.level.org.springframework.data.redis: "TRACE"
  logging.level.io.lettuce.core: "DEBUG"
  logging.level.org.springframework.data.redis.connection: "DEBUG"
  logging.level.org.springframework.data.redis.core: "DEBUG"
  logging.level.io.lettuce.core.protocol: "TRACE"
  logging.level.io.lettuce.core.cluster: "DEBUG"
  logging.level.io.netty: "DEBUG"