replicaCount: 1

image:
  repository: kye8780/auth-server
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: false

config:
  logging.level.org.springframework.data.redis: "TRACE"
  logging.level.io.lettuce.core: "DEBUG"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:mysql://dev-mysql.c14q2m426g1v.ap-northeast-2.rds.amazonaws.com:3306/user_db"
  SPRING_DATA_REDIS_CLUSTER_NODES: "truve-cache-prod.hjxi0v.clustercfg.apn2.cache.amazonaws.com:6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service.truve-kafka.svc.cluster.local:9092"
  SPRING_DATA_REDIS_CLUSTER_MAX_REDIRECTS: "10"
  SPRING_DATA_REDIS_CLUSTER_REFRESH_ADAPTIVE: "true"
  SPRING_DATA_REDIS_CLUSTER_REFRESH_PERIOD: "30s"