secrets:
  SPRING_MAIL_USERNAME: ""
  SPRING_MAIL_PASSWORD: ""
  SPRING_KAKAO_CLIENT_SECRET: ""
  KAKAO_CLIENT_ID: ""
  KAKAO_REDIRECT_URI: ""
  KAKAO_TOKEN_URL: ""
  NAVER_CLIENT_ID: ""
  NAVER_CLIENT_SECRET: ""
  NAVER_REDIRECT_URI: ""
  FRONT_OAUTH_CALLBACK: ""
  TOSS_SECRET_KEY: ""
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: ""
  SPRING_DATASOURCE_USERNAME: ""
  SPRING_DATASOURCE_PASSWORD: ""
  JWT_SECRET: ""
  SPRING_JPA_HIBERNATE_DDL_AUTO: ""