replicaCount: 1

image:
  repository: kye8780/musical
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8085

ingress:
  enabled: false

config:
  logging.level.org.springframework.data.redis: "TRACE"
  logging.level.io.lettuce.core: "DEBUG"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:mysql://dev-mysql.c14q2m426g1v.ap-northeast-2.rds.amazonaws.com:3306/musical_db"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka.truve-kafka.svc.cluster.local:9092"
  SPRING_DATA_REDIS_CLUSTER_NODES: "redis-headless.truve-redis.svc.cluster.local:6379"
  SPRING_DATA_REDIS_CLUSTER_MAX_REDIRECTS: "10"
  SPRING_DATA_REDIS_CLUSTER_REFRESH_ADAPTIVE: "true"
  SPRING_DATA_REDIS_CLUSTER_REFRESH_PERIOD: "30s"