global:
  clusterId: truve-eks-dev

nodeSelector:
  workload: system

tolerations:
  - key: workload
    operator: Equal
    value: system
    effect: NoSchedule

frontend:
  service:
    type: ClusterIP
  nodeSelector:
    workload: system
  tolerations:
    - key: workload
      operator: Equal
      value: system
      effect: NoSchedule

networkCosts:
  enabled: false

aggregator:
  nodeSelector:
    workload: system
  tolerations:
    - key: workload
      operator: Equal
      value: system
      effect: NoSchedule

forecasting:
  nodeSelector:
    workload: system
  tolerations:
    - key: workload
      operator: Equal
      value: system
      effect: NoSchedule

clusterController:
  nodeSelector:
    workload: system
  tolerations:
    - key: workload
      operator: Equal
      value: system
      effect: NoSchedule
