global:
  clusterId: truve-eks-dev

nodeSelector:
  workload: app

tolerations:
  - key: app
    operator: Equal
    value: app
    effect: NoSchedule

frontend:
  service:
    type: ClusterIP
  nodeSelector:
    workload: app
  tolerations:
    - key: workload
      operator: Equal
      value: app
      effect: NoSchedule

networkCosts:
  enabled: false

aggregator:
  nodeSelector:
    workload: app
  tolerations:
    - key: workload
      operator: Equal
      value: app
      effect: NoSchedule

forecasting:
  nodeSelector:
    workload: app
  tolerations:
    - key: workload
      operator: Equal
      value: app
      effect: NoSchedule

clusterController:
  nodeSelector:
    workload: app
  tolerations:
    - key: workload
      operator: Equal
      value: app
      effect: NoSchedule
