fullnameOverride: tempo

replicas: 1

serviceAccount:
  create: true
  name: tempo

persistence:
  enabled: true
  storageClassName: gp3
  size: 20Gi

service:
  type: ClusterIP

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

nodeSelector:
  workload: monitoring

tolerations:
  - key: workload
    operator: Equal
    value: monitoring
    effect: NoSchedule

tempo:
  reportingEnabled: false
  searchEnabled: false # 모놀리식으로 처음 붙이는 단계에서는 검색 기능까지 같이 켜면 readiness가 불안정해질 수 있어서, 초기 안정화는 search 끄고 trace 수집/저장만 먼저 확인하는 게 낫다.

  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  storage:
    trace:
      backend: s3
      s3:
        bucket: truve-dev-tempo-trace
        region: ap-northeast-2
        # prefix는 선택
        prefix: tempo
      # local:
      #   path: /var/tempo/traces

  server:
    http_listen_port: 3200
