grafana:
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: workload
      operator: Equal
      value: monitoring
      effect: NoSchedule
  persistence:
    enabled: true
    storageClassName: gp3
    accessModes: ['ReadWriteOnce']
    size: 10Gi
  adminUser: admin
  adminPassword: truve#12
  additionalDataSources: # Grafana에서 Tempo와 Loki를 데이터 소스로 추가하기 위한 설정
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.observability.svc.cluster.local:3100
      jsonData:
        maxLines: 1000
        derivedFields:
          - datasourceUid: tempo
            matcherRegex: "(\\w{32})" # 32자리 TraceID 매칭
            name: TraceID
            url: "$${__value.raw}"
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo.observability.svc.cluster.local:3200
      isDefault: false
      jsonData:
        httpMethod: GET
        lokiSearch:
          datasourceUid: Loki
        traceQuery:
          type: traceql
        serviceMap:
          datasourceUid: Prometheus
        nodeGraph:
          enabled: true
        traceToLogsV2:
          datasourceUid: Loki
          spanEndTimeShift: '5m'
          tags:
            - key: service.name
              value: service_name
            - key: k8s.namespace.name
              value: namespace
            - key: k8s.pod.name
              value: pod_name

prometheus:
  prometheusSpec:
    nodeSelector:
      workload: monitoring
    tolerations:
      - key: workload
        operator: Equal
        value: monitoring
        effect: NoSchedule
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ['ReadWriteOnce']
          resources:
            requests:
              storage: 50Gi

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      workload: monitoring
    tolerations:
      - key: workload
        operator: Equal
        value: monitoring
        effect: NoSchedule
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ['ReadWriteOnce']
          resources:
            requests:
              storage: 10Gi

kubeStateMetrics:
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: workload
      operator: Equal
      value: monitoring
      effect: NoSchedule

prometheusOperator:
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: workload
      operator: Equal
      value: monitoring
      effect: NoSchedule

nodeExporter:
  tolerations:
    - operator: Exists
