grafana:
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: workload
      operator: Equal
      value: monitoring
      effect: NoSchedule
  persistence:
    enabled: true
    storageClassName: gp3
    accessModes: ['ReadWriteOnce']
    size: 10Gi
  adminUser: admin
  adminPassword: truve#12
  additionalDataSources: # Grafana에서 Tempo를 데이터 소스로 추가하기 위한 설정
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo.observability.svc.cluster.local:3200
      isDefault: false
      jsonData:
        httpMethod: GET
        serviceMap:
          dataSourceUid: Prometheus # Tempo의 메트릭을 가져올 Prometheus 데이터 소스의 UID (자동 생성되므로 실제 UID로 변경 필요)
        traceToLogsV2:
          dataSourceUid: loki
          spanEndTimeShift: '5m'
          tags:
            - key: service.name
              value: service_name
            - key: k8s.namespace.name
              value: namespace
            - key: k8s.pod.name
              value: pod_name

prometheus:
  prometheusSpec:
    nodeSelector:
      workload: monitoring
    tolerations:
      - key: workload
        operator: Equal
        value: monitoring
        effect: NoSchedule
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ['ReadWriteOnce']
          resources:
            requests:
              storage: 50Gi

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      workload: monitoring
    tolerations:
      - key: workload
        operator: Equal
        value: monitoring
        effect: NoSchedule
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ['ReadWriteOnce']
          resources:
            requests:
              storage: 10Gi

kubeStateMetrics:
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: workload
      operator: Equal
      value: monitoring
      effect: NoSchedule

prometheusOperator:
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: workload
      operator: Equal
      value: monitoring
      effect: NoSchedule

nodeExporter:
  tolerations:
    - operator: Exists
