secrets:
  SPRING_DATASOURCE_USERNAME: ""
  SPRING_DATASOURCE_PASSWORD: ""
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: ""
  SPRING_JPA_HIBERNATE_DDL_AUTO: ""
  JWT_SECRET: ""
  USER_REDIS_HOST: ""
  USER_REDIS_PORT: ""