apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ .Values.nodeClass.name | quote }} # Karpenter가 AWS 노드를 만들 때 참조하는 노드 클래스 이름
spec:
  role: {{ .Values.nodeClass.role | quote }} # 새 EC2 노드에 연결할 IAM Role
  amiFamily: {{ .Values.nodeClass.amiFamily | quote }} # 사용할 OS/AMI 계열

  amiSelectorTerms: 
{{ toYaml .Values.nodeClass.amiSelectorTerms | nindent 4 }} # AMI 선택 조건 (예: alias: al2023@latest)

  subnetSelectorTerms: 
{{ toYaml .Values.nodeClass.subnetSelectorTerms | nindent 4 }} # 노드를 띄울 subnet 선택 조건

  securityGroupSelectorTerms: 
{{ toYaml .Values.nodeClass.securityGroupSelectorTerms | nindent 4 }} # 노드에 붙일 security group 선택 조건

  tags: 
{{ toYaml .Values.nodeClass.tags | nindent 4 }} # 노드에 붙일 security group 선택 조건
