{{- if .Values.appGeneralNodePool.enabled }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.appGeneralNodePool.name | quote }} # 일반 앱 워크로드용 NodePool 이름
spec:
  weight: {{ .Values.appGeneralNodePool.weight }} # 다른 NodePool과 비교 시 선택 가중치

  template:
    metadata:
      labels: 
{{ toYaml .Values.appGeneralNodePool.labels | nindent 8 }} # 이 NodePool로 생성된 노드에 붙는 라벨

    spec:
      nodeClassRef: # 어떤 EC2NodeClass 설정으로 노드를 만들지 연결
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Values.nodeClass.name | quote }}

      requirements: 
{{ toYaml .Values.appGeneralNodePool.requirements | nindent 8 }} # 노드 생성 시 만족해야 하는 제약 조건

      {{- with .Values.appGeneralNodePool.taints }}
      taints: 
{{ toYaml . | nindent 8 }} # 특정 워크로드만 올라오게 하는 제약
      {{- end }}

  disruption:
    consolidationPolicy: {{ .Values.appGeneralNodePool.disruption.consolidationPolicy | quote }} # 비어있거나 덜 쓰는 노드 정리 정책

    consolidateAfter: {{ .Values.appGeneralNodePool.disruption.consolidateAfter | quote }} # 노드 통합/정리 시작까지 대기 시간

  limits: 
{{ toYaml .Values.appGeneralNodePool.limits | nindent 4 }} 
{{- end }}