{{- if .Values.appStreamNodePool.enabled }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.appStreamNodePool.name }} # stream/worker 전용 NodePool 이름
spec:
  weight: {{ .Values.appStreamNodePool.weight }}

  template:
    metadata:
      labels: {{ toYaml .Values.appStreamNodePool.labels | nindent 8 }} # 생성된 노드에 stream 전용 라벨 부여
    spec: 
      nodeClassRef: # 어떤 AWS 노드 설정을 사용할지 지정
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Values.nodeClass.name }}

      requirements: {{ toYaml .Values.appStreamNodePool.requirements | nindent 8 }} # 인스턴스 타입, capacity type 등 제약 조건

      {{- with .Values.appStreamNodePool.taints }}
      taints: {{ toYaml . | nindent 8 }} # stream 전용 워크로드만 들어오게 taint 부여
      {{- end }}

  disruption:
    consolidationPolicy: {{ .Values.appStreamNodePool.disruption.consolidationPolicy }}
    consolidateAfter: {{ .Values.appStreamNodePool.disruption.consolidateAfter }}

  limits: {{ toYaml .Values.appStreamNodePool.limits | nindent 4 }} 
{{- end }}