{{- if .Values.appGeneralNodePool.enabled }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.appGeneralNodePool.name }} # 일반 앱 워크로드용 NodePool 이름
spec:
  weight: {{ .Values.appGeneralNodePool.weight }} # 다른 NodePool과 비교 시 선택 가중치

  template:
    metadata:
      labels: # 이 NodePool로 생성된 노드에 붙는 라벨
{{ toYaml .Values.appGeneralNodePool.labels | nindent 8 }}

    spec: # 어떤 EC2NodeClass 설정으로 노드를 만들지 연결
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Values.nodeClass.name }}

      requirements: # 노드 생성 시 만족해야 하는 제약 조건
{{ toYaml .Values.appGeneralNodePool.requirements | nindent 8 }}

      {{- with .Values.appGeneralNodePool.taints }}
      taints: # 특정 워크로드만 올라오게 하는 제약
{{ toYaml . | nindent 8 }}
      {{- end }}

  disruption:
    consolidationPolicy: {{ .Values.appGeneralNodePool.disruption.consolidationPolicy }} # 비어있거나 덜 쓰는 노드 정리 정책

    consolidateAfter: {{ .Values.appGeneralNodePool.disruption.consolidateAfter }} # 노드 통합/정리 시작까지 대기 시간

  limits: # NodePool 전체 확장 상한
{{ toYaml .Values.appGeneralNodePool.limits | nindent 4 }}
{{- end }}