loki:
  replicaCount: 1
  image:
    repository: grafana/loki
    tag: 2.8.2
    pullPolicy: IfNotPresent
  
  nodeSelector:
    workload: monitoring
  tolerations:
    - key: workload
      operator: Exists
      effect: NoSchedule

  persistence:
    enabled: true
    size: 10Gi
    storageClassName: gp3
    accessModes:
      - ReadWriteOnce

  loki:
    config: |
      auth_enabled: false
      server:
        http_listen_port: 3100
        log_level: info
      ingester:
        wal:
          enabled: true
          dir: /loki/wal
        lifecycler:
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
        chunk_idle_period: 5m
        max_chunk_age: 1h
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 168h
      storage_config:
        boltdb_shipper:
          active_index_directory: /loki/index
          cache_location: /loki/cache
          shared_store: filesystem
        filesystem:
          directory: /loki/chunks
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h

# 로그 수집기 (Fluent Bit 사용)
promtail:
  enabled: false
