replicaCount: 3

zookeeper:
  image: "confluentinc/cp-zookeeper:7.5.0"
  clientPort: 2181
  secureClientPort: 2888
  storage:
    size: 5Gi
    storageClassName: gp3

kafka:
  image: "confluentinc/cp-kafka:7.5.0"
  port: 9092
  replicationFactor: 3
  storage:
    size: 20Gi
    storageClassName: gp3

nodeSelector:
  workload: kafka

tolerations:
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 300
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 300
  - key: "workload"
    operator: "Equal"
    value: "kafka"
    effect: "NoSchedule"
