apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: truve-redis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: truve-secret-store
    kind: ClusterSecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/redis