apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: {{ .Chart.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-headless
  labels:
    app: {{ .Chart.Name }}
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
    - port: 16379
      targetPort: 16379
      name: cluster-bus
  selector:
    app: {{ .Chart.Name }}